// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-YO-7xJZXiDG_DOGXuhc1Byts2SXcsKY',
    appId: '1:999771098348:web:3a9d3005783a19ada969c9',
    messagingSenderId: '999771098348',
    projectId: 'flutter-auth-90bb2',
    authDomain: 'flutter-auth-90bb2.firebaseapp.com',
    storageBucket: 'flutter-auth-90bb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNatTvkVHhDJ8YxkLbxDV3GOzJQTUnSjc',
    appId: '1:999771098348:android:47d09da2f46a4a56a969c9',
    messagingSenderId: '999771098348',
    projectId: 'flutter-auth-90bb2',
    storageBucket: 'flutter-auth-90bb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc_6M1ii3Mo4e7lDi2SttN0tYHqfiCmJs',
    appId: '1:999771098348:ios:556fd65f316b0cc3a969c9',
    messagingSenderId: '999771098348',
    projectId: 'flutter-auth-90bb2',
    storageBucket: 'flutter-auth-90bb2.appspot.com',
    androidClientId: '999771098348-00g874s0nrqc1m0q8s8j99ds6o0s3a92.apps.googleusercontent.com',
    iosClientId: '999771098348-nrg032hafvmi7100ikr1g3mv9r3n58ub.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietdiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc_6M1ii3Mo4e7lDi2SttN0tYHqfiCmJs',
    appId: '1:999771098348:ios:ca03988a3d79b65da969c9',
    messagingSenderId: '999771098348',
    projectId: 'flutter-auth-90bb2',
    storageBucket: 'flutter-auth-90bb2.appspot.com',
    androidClientId: '999771098348-00g874s0nrqc1m0q8s8j99ds6o0s3a92.apps.googleusercontent.com',
    iosClientId: '999771098348-0k3f953pinj8poccb9ef0qib48d8e29s.apps.googleusercontent.com',
    iosBundleId: 'com.dietdietdone.dietdietdone.dietDone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-YO-7xJZXiDG_DOGXuhc1Byts2SXcsKY',
    appId: '1:999771098348:web:548a6740c38de170a969c9',
    messagingSenderId: '999771098348',
    projectId: 'flutter-auth-90bb2',
    authDomain: 'flutter-auth-90bb2.firebaseapp.com',
    storageBucket: 'flutter-auth-90bb2.appspot.com',
  );
}
