-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLmw5GlMNSAIm7Mkq
V9r7LlJU8axC6sW9eRcpuOmJvvygCgYIKoZIzj0DAQehRANCAAS4qvgzFZ+gZnb+
WmZkPYksuDol+QGofPChKY0Kyf1TyGQgJFuKV5V9ZnjqEgmk5JzWCTfJ07riWGl5
GOE8xlai
-----END PRIVATE KEY-----